### ISSUE TITLE
isdredditrecruiting.com is broken

### ISSUE THREAD

**Issue by aebe** [rickhull/rickhull.github.io#1]
People on TEST forums (Yolo Swagtron in particular) are interested in helping to fix it or probably maintain it themselves, if you are no longer interested.

**Comment by rickhull** [comment]
It was a joke I made, right around the time dredditisrecruiting.com was created.  I think it's working "as intended".  The payload is a tiny file with no extension with contents:

```
YES
```

Due to mime-types or some shit, most browsers attempt to download the file rather than display it.  which also makes people think they're being hacked or something.

It's a total troll.  That said, I'd be happy to transfer the domain to you guys, or maybe put something better in its place.  I don't have a ton of bandwidth for this right now.  LMK what you guys want to do.
